import json

notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {"provenance": [], "gpuType": "T4"},
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "accelerator": "GPU"
    },
    "cells": [
        {
            "cell_type": "markdown",
            "source": [
                "# 🐄 Teknova AI Animal Tracking API\n",
                "\n",
                "**Ücretsiz T4 GPU ile Hayvan Tanıma Sistemi**\n",
                "\n",
                "## 📋 Kullanım:\n",
                "1. `Runtime` → `Change runtime type` → **T4 GPU** seçin\n",
                "2. Tüm hücreleri sırayla çalıştırın\n",
                "3. ngrok token'ınızı girin\n",
                "4. Son hücredeki **URL**'i iOS uygulamasına yapıştırın\n",
                "\n",
                "---"
            ],
            "metadata": {"id": "header"}
        },
        {
            "cell_type": "code",
            "source": [
                "# 1️⃣ GPU Kontrolü\n",
                "!nvidia-smi --query-gpu=name,memory.total --format=csv\n",
                "print('✅ GPU hazır!')"
            ],
            "metadata": {"id": "gpu"},
            "execution_count": None,
            "outputs": []
        },
        {
            "cell_type": "code",
            "source": [
                "# 2️⃣ Bağımlılıkları Kur (~2 dk)\n",
                "!pip install -q fastapi uvicorn python-multipart pyngrok ultralytics opencv-python-headless pillow nest-asyncio\n",
                "print('✅ Paketler kuruldu!')"
            ],
            "metadata": {"id": "install"},
            "execution_count": None,
            "outputs": []
        },
        {
            "cell_type": "code",
            "source": [
                "# 3️⃣ ngrok Token Ayarla\n",
                "# 1. https://dashboard.ngrok.com/signup - Ücretsiz hesap aç\n",
                "# 2. https://dashboard.ngrok.com/get-started/your-authtoken - Token'ı kopyala\n",
                "# 3. Aşağıya yapıştır\n",
                "\n",
                "NGROK_TOKEN = ''  # @param {type:\"string\"}\n",
                "\n",
                "if NGROK_TOKEN:\n",
                "    from pyngrok import ngrok\n",
                "    ngrok.set_auth_token(NGROK_TOKEN)\n",
                "    print('✅ ngrok token ayarlandı!')\n",
                "else:\n",
                "    print('⚠️ ngrok token gerekli! Yukarıdaki linke git ve token al.')"
            ],
            "metadata": {"id": "ngrok"},
            "execution_count": None,
            "outputs": []
        },
        {
            "cell_type": "code",
            "source": [
                "%%writefile app.py\n",
                "import io, time\n",
                "from typing import List, Optional\n",
                "from collections import defaultdict\n",
                "import numpy as np\n",
                "import cv2\n",
                "from fastapi import FastAPI, File, UploadFile, HTTPException\n",
                "from fastapi.middleware.cors import CORSMiddleware\n",
                "from pydantic import BaseModel\n",
                "from ultralytics import YOLO\n",
                "\n",
                "# Config\n",
                "ANIMAL_IDS = {14,15,16,17,18,19,20,21,22,23}\n",
                "NAMES = {14:'bird',15:'cat',16:'dog',17:'horse',18:'sheep',19:'cow',20:'elephant',21:'bear',22:'zebra',23:'giraffe'}\n",
                "TR = {'cow':'INEK','sheep':'KOYUN','horse':'AT','dog':'KOPEK','cat':'KEDI','bird':'KUS','elephant':'FIL','bear':'AYI','zebra':'ZEBRA','giraffe':'ZURAFA'}\n",
                "\n",
                "class Animal(BaseModel):\n",
                "    track_id: int\n",
                "    animal_id: str\n",
                "    class_name: str\n",
                "    bbox: List[int]\n",
                "    confidence: float\n",
                "    re_id_confidence: float\n",
                "    is_identified: bool = True\n",
                "    is_new: bool = False\n",
                "    velocity: List[float] = [0.0, 0.0]\n",
                "    direction: float = 0.0\n",
                "    health_score: Optional[float] = None\n",
                "    behavior: Optional[str] = None\n",
                "\n",
                "class Result(BaseModel):\n",
                "    frame_id: int\n",
                "    timestamp: float\n",
                "    fps: float\n",
                "    animal_count: int\n",
                "    total_registered: int\n",
                "    new_this_frame: int\n",
                "    animals: List[Animal]\n",
                "    frame_size: List[int]\n",
                "\n",
                "class FE:\n",
                "    def extract(self, img, bbox):\n",
                "        x1,y1,x2,y2 = [int(v) for v in bbox]\n",
                "        h,w = img.shape[:2]\n",
                "        x1,y1,x2,y2 = max(0,x1),max(0,y1),min(w,x2),min(h,y2)\n",
                "        if x2<=x1 or y2<=y1: return None\n",
                "        crop = img[y1:y2,x1:x2]\n",
                "        if crop.size==0: return None\n",
                "        try: crop = cv2.resize(crop,(128,256))\n",
                "        except: return None\n",
                "        hsv = cv2.cvtColor(crop,cv2.COLOR_BGR2HSV)\n",
                "        feats = []\n",
                "        for i,b in enumerate([32,32,16]):\n",
                "            hist = cv2.calcHist([hsv],[i],None,[b],[0,256 if i>0 else 180])\n",
                "            cv2.normalize(hist,hist)\n",
                "            feats.append(hist.flatten())\n",
                "        hc = crop.shape[0]\n",
                "        for r in [crop[:hc//3],crop[hc//3:2*hc//3],crop[2*hc//3:]]:\n",
                "            hr = cv2.calcHist([cv2.cvtColor(r,cv2.COLOR_BGR2HSV)],[0],None,[32],[0,180])\n",
                "            cv2.normalize(hr,hr)\n",
                "            feats.append(hr.flatten())\n",
                "        c = np.concatenate(feats)\n",
                "        n = np.linalg.norm(c)\n",
                "        return (c/n).astype(np.float32) if n>0 else c.astype(np.float32)\n",
                "\n",
                "class Gallery:\n",
                "    def __init__(s): s.r,s.f,s.c,s.idx = {},{},defaultdict(int),defaultdict(list)\n",
                "    def gen_id(s,cn):\n",
                "        p = TR.get(cn.lower(),cn.upper()[:4])\n",
                "        s.c[p]+=1\n",
                "        return f'{p}_{s.c[p]:04d}'\n",
                "    def add(s,f,cn,cf):\n",
                "        aid = s.gen_id(cn)\n",
                "        s.r[aid] = {'animal_id':aid,'class_name':cn,'first_seen':time.time(),'last_seen':time.time(),'total_detections':1,'best_confidence':cf}\n",
                "        s.f[aid] = f.copy()\n",
                "        s.idx[cn].append(aid)\n",
                "        print(f'🆕 Yeni: {aid}')\n",
                "        return aid\n",
                "    def search(s,q,cn):\n",
                "        if cn not in s.idx: return []\n",
                "        qn = q/(np.linalg.norm(q)+1e-8)\n",
                "        return sorted([(a,float(np.dot(qn,s.f[a]/(np.linalg.norm(s.f[a])+1e-8)))) for a in s.idx[cn] if a in s.f],key=lambda x:-x[1])[:5]\n",
                "    def update(s,aid,f):\n",
                "        if aid in s.f:\n",
                "            s.f[aid] = 0.98*s.f[aid]+0.02*f\n",
                "            s.r[aid]['last_seen']=time.time()\n",
                "            s.r[aid]['total_detections']+=1\n",
                "    def reset(s): s.r.clear();s.f.clear();s.c.clear();s.idx.clear();print('🗑️ Galeri sıfırlandı')\n",
                "    @property\n",
                "    def size(s): return len(s.r)\n",
                "\n",
                "class Detector:\n",
                "    def __init__(s):\n",
                "        print('🔄 YOLOv8 yükleniyor...')\n",
                "        s.m = YOLO('yolov8n.pt')\n",
                "        print('✅ Model hazır!')\n",
                "        s.e,s.g,s.fc,s.tid = FE(),Gallery(),0,0\n",
                "    def process(s,img):\n",
                "        t0 = time.time()\n",
                "        s.fc+=1\n",
                "        h,w = img.shape[:2]\n",
                "        animals,new,used = [],0,set()\n",
                "        res = s.m(img,verbose=False,conf=0.4)\n",
                "        dets = []\n",
                "        for r in res:\n",
                "            if r.boxes is None: continue\n",
                "            for b in r.boxes:\n",
                "                cid = int(b.cls[0].item())\n",
                "                if cid not in ANIMAL_IDS: continue\n",
                "                cn = NAMES.get(cid,'unknown')\n",
                "                bb = [int(v) for v in b.xyxy[0].cpu().numpy()]\n",
                "                cf = float(b.conf[0].item())\n",
                "                f = s.e.extract(img,bb)\n",
                "                if f is not None: dets.append({'bb':bb,'cf':cf,'cn':cn,'f':f})\n",
                "        dets.sort(key=lambda x:-x['cf'])\n",
                "        for d in dets:\n",
                "            s.tid+=1\n",
                "            ms = s.g.search(d['f'],d['cn'])\n",
                "            bm = next(((a,sim) for a,sim in ms if a not in used and sim>=0.92),None)\n",
                "            if bm:\n",
                "                aid,sim = bm\n",
                "                used.add(aid)\n",
                "                s.g.update(aid,d['f'])\n",
                "                isn = False\n",
                "            else:\n",
                "                aid = s.g.add(d['f'],d['cn'],d['cf'])\n",
                "                used.add(aid)\n",
                "                sim,isn,new = 1.0,True,new+1\n",
                "            animals.append(Animal(track_id=s.tid,animal_id=aid,class_name=d['cn'],bbox=d['bb'],confidence=d['cf'],re_id_confidence=sim,is_new=isn))\n",
                "        el = time.time()-t0\n",
                "        return Result(frame_id=s.fc,timestamp=time.time(),fps=1/el if el>0 else 0,animal_count=len(animals),total_registered=s.g.size,new_this_frame=new,animals=animals,frame_size=[w,h])\n",
                "\n",
                "app = FastAPI(title='Teknova AI Animal Tracking')\n",
                "app.add_middleware(CORSMiddleware,allow_origins=['*'],allow_credentials=True,allow_methods=['*'],allow_headers=['*'])\n",
                "det = None\n",
                "\n",
                "@app.on_event('startup')\n",
                "async def startup(): global det; det=Detector()\n",
                "\n",
                "@app.get('/')\n",
                "async def root(): return {'name':'Teknova AI Animal Tracking','status':'running','gpu':'T4'}\n",
                "\n",
                "@app.get('/health')\n",
                "async def health(): return {'status':'healthy','gpu':'T4','gallery_size':det.g.size if det else 0}\n",
                "\n",
                "@app.post('/api/v1/detection/process-frame')\n",
                "async def process_frame(file:UploadFile=File(...)):\n",
                "    if not det: raise HTTPException(503,'Detector not ready')\n",
                "    contents = await file.read()\n",
                "    img = cv2.imdecode(np.frombuffer(contents,np.uint8),cv2.IMREAD_COLOR)\n",
                "    if img is None: raise HTTPException(400,'Invalid image')\n",
                "    return det.process(img).model_dump()\n",
                "\n",
                "@app.get('/api/v1/detection/gallery')\n",
                "async def get_gallery():\n",
                "    if not det: return {'total':0,'animals':[],'by_class':{}}\n",
                "    return {'total':det.g.size,'animals':list(det.g.r.values()),'by_class':{k:len(v) for k,v in det.g.idx.items()}}\n",
                "\n",
                "@app.post('/api/v1/detection/reset')\n",
                "async def reset():\n",
                "    if det: det.g.reset()\n",
                "    return {'status':'success','message':'Gallery reset'}"
            ],
            "metadata": {"id": "app"},
            "execution_count": None,
            "outputs": []
        },
        {
            "cell_type": "code",
            "source": [
                "# 5️⃣ SUNUCUYU BAŞLAT 🚀\n",
                "import nest_asyncio\n",
                "nest_asyncio.apply()\n",
                "\n",
                "from pyngrok import ngrok\n",
                "import uvicorn\n",
                "\n",
                "# ngrok tunnel\n",
                "public_url = ngrok.connect(8000)\n",
                "\n",
                "print('='*60)\n",
                "print('🎉 TEKNOVA AI SUNUCUSU HAZIR!')\n",
                "print('='*60)\n",
                "print()\n",
                "print('📱 iOS Uygulamasına Bu URL\\'i Yapıştır:')\n",
                "print()\n",
                "print(f'   {public_url}')\n",
                "print()\n",
                "print('='*60)\n",
                "print('⚠️  Bu pencereyi AÇIK TUT - kapatırsan sunucu durur!')\n",
                "print('='*60)\n",
                "print()\n",
                "print('🧪 Test:')\n",
                "print(f'   curl {public_url}/health')\n",
                "print()\n",
                "\n",
                "# Sunucuyu başlat\n",
                "uvicorn.run('app:app', host='0.0.0.0', port=8000)"
            ],
            "metadata": {"id": "run"},
            "execution_count": None,
            "outputs": []
        }
    ]
}

# Save notebook
with open('/Users/onerozbey/Desktop/ai_goruntu_isleme/colab/Teknova_Animal_Tracking.ipynb', 'w') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print('✅ Notebook oluşturuldu!')
print('📁 Konum: /Users/onerozbey/Desktop/ai_goruntu_isleme/colab/Teknova_Animal_Tracking.ipynb')
