#!/bin/bash
# ===========================================
# Supabase Setup Guide & Script
# ===========================================

echo "🗄️ Supabase Setup Guide"
echo "========================"
echo ""
echo "Follow these steps to setup Supabase:"
echo ""
echo "1. Go to https://supabase.com and create an account"
echo "2. Create a new project"
echo "3. Once project is created, go to Settings > API"
echo "4. Copy the following values:"
echo "   - Project URL (looks like: https://xxxxx.supabase.co)"
echo "   - anon public key (starts with: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...)"
echo ""
echo "5. Update frontend/.env.local with these values:"
echo "   NEXT_PUBLIC_SUPABASE_URL=https://xxxxx.supabase.co"
echo "   NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key"
echo ""
echo "6. Go to SQL Editor in Supabase Dashboard"
echo "7. Copy and paste the contents of supabase/schema.sql"
echo "8. Run the SQL to create all tables"
echo ""
echo "9. (Optional) Enable Row Level Security (RLS):"
echo "   - Go to Authentication > Policies"
echo "   - Create policies for each table"
echo ""
echo "=========================================="
echo ""
echo "To apply schema automatically, install Supabase CLI:"
echo "  brew install supabase/tap/supabase"
echo ""
echo "Then run:"
echo "  supabase init"
echo "  supabase link --project-ref YOUR_PROJECT_REF"
echo "  supabase db push"
echo ""
